spring:
  application:
    name: wjs-cash
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/cash?characterEncoding=utf-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true
      username: root
      password: yueshen521
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  rabbitmq:
    host: 172.16.10.147
    username: admin
    password: admin
  # 热部署配置开启
  devtools:
    restart:
      enabled: true
mybatis-plus:
  mapper-locations:  classpath:**/mapper/**/*.xml
  global-config:
    db-config:
      column-underline: true
  configuration:
    map-underscore-to-camel-case: true
auth:
  user:
    token-header: Authorization
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
redis:
  host: 127.0.0.1
  port: 6379
  password:
  lettuce:
    pool:
      max-active: 50
      max-idle: 20
      max-wait: 60s
      min-idle: 5



